package cn.zhengzhaoyu.personalPage.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("p_article", "id", Article.class);
		arp.addMapping("p_comment", "id", Comment.class);
		arp.addMapping("p_log", "id", Log.class);
		arp.addMapping("p_picture", "id", Picture.class);
		arp.addMapping("p_word", "id", Word.class);
	}
}

