package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BaseArticleType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleType extends BaseArticleType<ArticleType> {
	
}
