package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.safe.JsoupFilter;
import cn.zhengzhaoyu.personalPage.common.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
    @Override
    protected void filter(int filterBy) {
        JsoupFilter.filterComment(this);
    }
}
