package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BaseEmail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Email extends BaseEmail<Email> {
	
}
