package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	
}
