package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BasePictureType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PictureType extends BasePictureType<PictureType> {
	
}
