package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	
}
