package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BaseWord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Word extends BaseWord<Word> {
	
}
