package cn.zhengzhaoyu.personalPage.common.model;

import cn.zhengzhaoyu.personalPage.common.model.base.BaseWord;
import cn.zhengzhaoyu.personalPage.common.safe.JsoupFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Word extends BaseWord<Word> {
    @Override
    protected void filter(int filterBy) {
        JsoupFilter.filterWord(this);
    }

}
