package cn.zhengzhaoyu.personalPage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setArticleText(java.lang.String articleText) {
		set("article_text", articleText);
		return (M)this;
	}

	public java.lang.String getArticleText() {
		return get("article_text");
	}

	public M setArticleTime(java.util.Date articleTime) {
		set("article_time", articleTime);
		return (M)this;
	}

	public java.util.Date getArticleTime() {
		return get("article_time");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setArticleAbstract(java.lang.String articleAbstract) {
		set("article_abstract", articleAbstract);
		return (M)this;
	}

	public java.lang.String getArticleAbstract() {
		return get("article_abstract");
	}

}
