package cn.zhengzhaoyu.personalPage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
		return (M)this;
	}

	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

	public M setCommentText(java.lang.String commentText) {
		set("comment_text", commentText);
		return (M)this;
	}

	public java.lang.String getCommentText() {
		return get("comment_text");
	}

	public M setCommentName(java.lang.String commentName) {
		set("comment_name", commentName);
		return (M)this;
	}

	public java.lang.String getCommentName() {
		return get("comment_name");
	}

	public M setParent(java.lang.Integer parent) {
		set("parent", parent);
		return (M)this;
	}

	public java.lang.Integer getParent() {
		return get("parent");
	}

}
