package cn.zhengzhaoyu.personalPage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setOprateTime(java.util.Date oprateTime) {
		set("oprate_time", oprateTime);
		return (M)this;
	}

	public java.util.Date getOprateTime() {
		return get("oprate_time");
	}

	public M setOprateIp(java.lang.String oprateIp) {
		set("oprate_ip", oprateIp);
		return (M)this;
	}

	public java.lang.String getOprateIp() {
		return get("oprate_ip");
	}

}
