package cn.zhengzhaoyu.personalPage.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticleType<M extends BaseArticleType<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
		return (M)this;
	}

	public java.lang.String getTypeName() {
		return get("type_name");
	}

}
